package com.cybervet.model.enums;

public enum UserState {
    nothing,
    START,
    CHOOSE_A_DIET,
    MAIN_MENU,
    ADDING_PET,
    ASKING_PET_TYPE,
    ASKING_CAT_BREED,
    CHOOSING_CAT_BREED,
    CHOOSING_DOG_BREED,
    SHOOSING_CAT_BREED,
    ASKING_AGE,
    ASKING_WEIGHT,
    ASKING_ACTIVITY, SAVING_PET, CHOOSING_BREED
}
